export const dummyTowers = [
  {
    id: "TWR-001",
    name: "Tower Alpha",
    location: { lat: 25.2048, lng: 55.2708, city: "Dubai, UAE" },
    status: "online",
    battery: 87,
    temperature: 42,
    uptime: 99.2,
    networkLoad: 65,
    useCase: "Smart City",
    region: "Middle East",
    lastMaintenance: "2024-01-15",
    components: ["5G Module", "IoT Sensors", "Edge Computing Unit"],
    model3D: {
      hasCustomModel: false,
      modelUrl: null,
      modelType: null,
      scale: 2.0,
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      lastUpdated: null
    }
  },
  {
    id: "TWR-002",
    name: "Tower Beta",
    location: { lat: 48.8566, lng: 2.3522, city: "Paris, France" },
    status: "warning",
    battery: 23,
    temperature: 18,
    uptime: 94.8,
    networkLoad: 82,
    useCase: "Industrial IoT",
    region: "Europe",
    lastMaintenance: "2024-01-10",
    components: ["Industrial Sensors", "Edge AI Unit", "Weather Station"],
  },
  {
    id: "TWR-003",
    name: "Tower Gamma",
    location: { lat: 33.8869, lng: 35.5131, city: "Beirut, Lebanon" },
    status: "critical",
    battery: 8,
    temperature: 55,
    uptime: 78.5,
    networkLoad: 95,
    useCase: "Emergency Response",
    region: "Middle East",
    lastMaintenance: "2023-12-28",
    components: ["Emergency Beacon", "Satellite Link", "Backup Power"],
  },
  {
    id: "TWR-004",
    name: "Tower Delta",
    location: { lat: 40.7128, lng: -74.0060, city: "New York, USA" },
    status: "online",
    battery: 92,
    temperature: 22,
    uptime: 99.8,
    networkLoad: 45,
    useCase: "Smart City",
    region: "North America",
    lastMaintenance: "2024-01-12",
    components: ["5G Module", "Traffic Sensors", "Air Quality Monitor"],
  },
  {
    id: "TWR-005",
    name: "Tower Echo",
    location: { lat: 35.6762, lng: 139.6503, city: "Tokyo, Japan" },
    status: "online",
    battery: 78,
    temperature: 28,
    uptime: 98.9,
    networkLoad: 72,
    useCase: "Industrial IoT",
    region: "Asia Pacific",
    lastMaintenance: "2024-01-08",
    components: ["Industrial Sensors", "Robotics Controller", "Quality Control"],
  },
  {
    id: "TWR-006",
    name: "Tower Foxtrot",
    location: { lat: -33.8688, lng: 151.2093, city: "Sydney, Australia" },
    status: "warning",
    battery: 34,
    temperature: 35,
    uptime: 96.2,
    networkLoad: 88,
    useCase: "Smart City",
    region: "Asia Pacific",
    lastMaintenance: "2024-01-05",
    components: ["5G Module", "Weather Station", "Solar Panel Controller"],
  },
  {
    id: "TWR-007",
    name: "Tower Golf",
    location: { lat: -23.5505, lng: -46.6333, city: "São Paulo, Brazil" },
    status: "online",
    battery: 81,
    temperature: 38,
    uptime: 97.5,
    networkLoad: 58,
    useCase: "Emergency Response",
    region: "South America",
    lastMaintenance: "2024-01-14",
    components: ["Emergency Beacon", "Medical Sensors", "Traffic Control"],
  },
  {
    id: "TWR-008",
    name: "Tower Hotel",
    location: { lat: 30.0444, lng: 31.2357, city: "Cairo, Egypt" },
    status: "critical",
    battery: 12,
    temperature: 62,
    uptime: 82.1,
    networkLoad: 91,
    useCase: "Industrial IoT",
    region: "Africa",
    lastMaintenance: "2023-12-20",
    components: ["Industrial Sensors", "Power Grid Monitor", "Water Quality Sensor"],
  },
  {
    id: "TWR-009",
    name: "Tower India",
    location: { lat: 19.0760, lng: 72.8777, city: "Mumbai, India" },
    status: "online",
    battery: 69,
    temperature: 41,
    uptime: 95.8,
    networkLoad: 76,
    useCase: "Smart City",
    region: "Asia Pacific",
    lastMaintenance: "2024-01-11",
    components: ["5G Module", "Crowd Sensors", "Public Transport Tracker"],
  },
  {
    id: "TWR-010",
    name: "Tower Juliet",
    location: { lat: 55.7558, lng: 37.6176, city: "Moscow, Russia" },
    status: "warning",
    battery: 29,
    temperature: -5,
    uptime: 93.4,
    networkLoad: 84,
    useCase: "Industrial IoT",
    region: "Europe",
    lastMaintenance: "2024-01-03",
    components: ["Industrial Sensors", "Temperature Monitor", "Heating Controller"],
  },
]

export const dummyAlerts = [
  {
    id: "ALT-001",
    timestamp: "2024-01-16T10:30:00Z",
    message: "Battery level critically low",
    severity: "critical",
    towerId: "TWR-003",
    towerName: "Tower Gamma",
    resolved: false,
  },
  {
    id: "ALT-002",
    timestamp: "2024-01-16T09:15:00Z",
    message: "High network load detected",
    severity: "warning",
    towerId: "TWR-002",
    towerName: "Tower Beta",
    resolved: false,
  },
  {
    id: "ALT-003",
    timestamp: "2024-01-16T08:45:00Z",
    message: "Routine maintenance completed",
    severity: "info",
    towerId: "TWR-001",
    towerName: "Tower Alpha",
    resolved: true,
  },
]

export const dummyAIInsights = [
  {
    id: "AI-001",
    towerId: "TWR-003",
    towerName: "Tower Gamma",
    prediction: "Battery will fail in 4 days",
    recommendation: "Schedule immediate battery replacement",
    confidence: 94,
    riskType: "Hardware Failure",
    urgency: "critical",
  },
  {
    id: "AI-002",
    towerId: "TWR-002",
    towerName: "Tower Beta",
    prediction: "CPU overload risk: 87%",
    recommendation: "Optimize workload distribution",
    confidence: 87,
    riskType: "Performance",
    urgency: "warning",
  },
]

export const dummyTelemetryData = [
  { time: "00:00", voltage: 12.4, temperature: 42, bandwidth: 65 },
  { time: "04:00", voltage: 12.1, temperature: 38, bandwidth: 45 },
  { time: "08:00", voltage: 12.3, temperature: 44, bandwidth: 78 },
  { time: "12:00", voltage: 12.0, temperature: 48, bandwidth: 89 },
  { time: "16:00", voltage: 11.8, temperature: 52, bandwidth: 92 },
  { time: "20:00", voltage: 11.9, temperature: 46, bandwidth: 71 },
]
